### ISSUE TITLE
不能兼容Triggernometry 1.0.7.2

### ISSUE THREAD

**Issue by xyuelin** [TundraWork/FFXIV_ACT_Plugin_CN#1]
原版ACT，加载这个解析后，再加载Triggernometry 报错。

用无猫的自整合解析插件则没有问题

**Comment by TundraWork** [comment]
Triggernometry 不兼容的问题之前已经与作者多次沟通未果，目前该插件已开源，考虑 5.0 更新后提供绿色版 ACT 可用版本。
