### ISSUE TITLE
6.0解析插件加载不了

### ISSUE THREAD

**Issue by tssailzz8** [TundraWork/FFXIV_ACT_Plugin_CN#10]
![image](https://user-images.githubusercontent.com/52206101/158798392-4da2eaf4-a95d-48bc-9a58-84af7343f347.png)
![6OG6~F)%{IFSKM@7G`9F(VV](https://user-images.githubusercontent.com/52206101/158798454-6ada1c15-a68e-4160-85d3-51d6bdbbd000.png)
![3KPYX)1C ZJYST(TBHW$LCO](https://user-images.githubusercontent.com/52206101/158798462-6652803c-fefb-4388-8dcd-a5e973dc4ff6.png)

**Comment by TundraWork** [comment]
Working on a fix

**Comment by TundraWork** [comment]
Should be fixed in https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/releases/tag/2.22.3.2
