### ISSUE TITLE
最新的解析

### ISSUE THREAD

**Issue by tabeboo** [TundraWork/FFXIV_ACT_Plugin_CN#11]
大佬最新的国服解析插件加载不了呀

**Comment by TundraWork** [comment]
无法复现，请提供有效详细的问题信息

**Comment by hyskylord** [comment]
---------------------------
Load Error
---------------------------
未能加载文件或程序集“Advanced Combat Tracker, Version=3.5.0.273, Culture=neutral, PublicKeyToken=a946b61e93d97868”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)


---------------------------
确定   
---------------------------
---------------------------
Invalid Plugin
---------------------------
This assembly does not have a class that implements ACT's plugin interface, or scanning the assembly threw an error.
---------------------------
确定   
---------------------------

**Comment by tabeboo** [comment]
> 无法复现，请提供有效详细的问题信息

System.TypeLoadException: 未能从程序集“FFXIV_ACT_Plugin.Resource, Version=2.0.4.6, Culture=neutral, PublicKeyToken=null”中加载类型“FFXIV_ACT_Plugin.Resource.ResourceManager”。
   在 FFXIV_ACT_Plugin.FFXIV_ACT_Plugin.InitPlugin(TabPage pluginScreenSpace, Label pluginStatusText)
   在 Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)

**Comment by TundraWork** [comment]
@hyskylord 不是一个问题，我无法复现你的问题，试试使用最新版本的ACT

**Comment by TundraWork** [comment]
@tabeboo 你要加载的解析插件看起来不是最新版本。

**Comment by hyskylord** [comment]
@TundraWork ACT最新版是3.6.0.275版本 是不是引用太旧了，插件不应该试图加载3.5.0.273版本才对

**Comment by TundraWork** [comment]
@TundraWork 对ACT的依赖引用是没有强制版本的，我们测试ACT 3.5/3.6版本均可正常加载。你可以试试用一个干净全新的ACT加载是否成功，如果成功则不是我们的问题。

**Comment by TundraWork** [comment]
由于问题无效关闭。
