### ISSUE TITLE
新版插件不能用改名后的ACT加载

### ISSUE THREAD

**Issue by hyskylord** [TundraWork/FFXIV_ACT_Plugin_CN#12]
错误信息在#11 提到了，研究发现新版的插件只能用原名的Advanced Combat Tracker.exe加载，重命名后就会报错。因为比较需要改名来保存不同的ACT设置（比如区分国服和国际服），所以希望能够优化一下。

**Comment by TundraWork** [comment]
Working on a solution.

**Comment by TundraWork** [comment]
Should fixed in https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/releases/tag/2.22.3.3
