### ISSUE TITLE
6.1的没问题，6.15的出现了不统计伤害的问题

### ISSUE THREAD

**Issue by examrl** [TundraWork/FFXIV_ACT_Plugin_CN#13]
美化无数据进入，act本身也记录不到伤害，触发器正常报机制。

**Comment by TundraWork** [comment]
无法复现，请和其他用户沟通确认可复现.

**Comment by examrl** [comment]
也不知道怎么就解决了。一直重启act，然后解析就报错了，再也打不上勾了，然后就重新下了一份，好像就正常了。。。迷惑

打扰了

**Comment by TundraWork** [comment]
mark as solved
