### ISSUE TITLE
Not working well

### ISSUE THREAD

**Issue by VittorioNier** [TundraWork/FFXIV_ACT_Plugin_CN#15]
it seems can't work after hotfix

**Comment by sandtechnology** [comment]
https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/releases/tag/2.23.1.1

**Comment by TundraWork** [comment]
Please use our latest [pre-release version](https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/releases/tag/2.23.1.1).

As a kindly note, we prefer to use pre-release for new versions as they are auto-generated artifacts and we do not test them manually.
