### ISSUE TITLE
not compatible with FFXIV CN 5.20

### ISSUE THREAD

**Issue by haojunsui** [TundraWork/FFXIV_ACT_Plugin_CN#4]
Cannot successfully generate battle log for OverlayPlugin.dll to consume

**Comment by TundraWork** [comment]
Please provide more details, or I can't understand your case clearly.

I guess it's an issue of your OverlayPlugin/ngld version.

FYI, we have our own version of ngld & cactbot working well with https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/releases/tag/2.20.7.1 .

**Comment by haojunsui** [comment]
Release 2.20.5.1 used to work with latest version of ngld & cactbot. Does the pre-release have to work with a specific verison of ngld & cactbot?

**Comment by emo64** [comment]
I have the same issue.  There is a serveral times my overlay plugin suddently works and display some wrong data. For example, a white mage has only 500 dps in eden raid. It seems to be related to another issue https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/issues/5
![image](https://user-images.githubusercontent.com/7891878/88090848-c22b5300-cbc0-11ea-963a-5143c0d35b18.png)

**Comment by TundraWork** [comment]
> I have the same issue.  There is a serveral times my overlay plugin suddently works and display some wrong data. For example, a white mage has only 500 dps in eden raid. It seems to be related to another issue https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/issues/5
> ![image](https://user-images.githubusercontent.com/7891878/88090848-c22b5300-cbc0-11ea-963a-5143c0d35b18.png)
> 

Yes, this is what #5 means.

**Comment by TundraWork** [comment]
> Release 2.20.5.1 used to work with latest version of ngld & cactbot. Does the pre-release have to work with a specific verison of ngld & cactbot?

No. AFAIK it should work with any versions of OverlayPlugin/ngld. FFXIV_ACT_Plugin nearly never changed its log format so if you can't see DPS/HPS in your OverlayPlugin, it seems FFXIV_ACT_Plugin itself is not working.

**Comment by TundraWork** [comment]
Please try the new release 2.20.7.2.

**Comment by haojunsui** [comment]
Release 2.20.7.2 resolves the problem. Thank you for the quick response
