### ISSUE TITLE
Failed to apply localization file.

### ISSUE THREAD

**Issue by iuun473** [TundraWork/FFXIV_ACT_Plugin_CN#6]
Sysele.lleferenceException:未将对象引用设置到对象的实例。
在RinbowMage AcianioericeaicinFgreee
在RainbowMage. Actloalizelocalizere.ocalize

首次出现该问题，原版act 3.4.8.270
添加插件后显示started，但是无法解析，
重新打开act会报出上述错误
act安装路径没有中文

**Comment by TundraWork** [comment]
It's likely that your ACT Localization Plugin is out-of-date. Try using a newer version. If the error persists, maybe you should find another fork of Localization Plugin.

FYI, the Localization Plugin in ACT Diemoe works well.

**Comment by iuun473** [comment]
I think you are right
